---
# tasks file for jenkins
- name: install open jdk
  apt:
    name: openjdk-11-jre-headless
    state: present

- name: Add jenkins GPG key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: add jenkins repo
  shell: echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list

- name: update repo
  apt:
    update_cache: yes

- name: install jenkins
  apt:
    name: jenkins
    state: present

- name: start jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
    
- name: Change file ownership, [ docker.sock ]
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: jenkins

- name: dont ask for password when login to jenkins
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^jenkins ALL'
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
