---

- name: start jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: enable UFW
  ufw:
    state: enabled
    policy: allow

- name: reload ufw
  ufw:
    state: reloaded
