- name: DevOps Task
  become: yes
  hosts: aws

  pre_tasks:
    - name: Update apt cache 
      apt:
        update_cache: yes

  roles:
    - nginx
    - docker
    - jenkins
    - ufw

  















